### ISSUE TITLE
Test failure in 0.2.6 

### ISSUE THREAD

**Issue by max-baz** [Gskartwii/teehee#12]
Hi there,

I'm running tests as part of AUR package, and it shows one failed test, which I can also reproduce manually 😉 

It's mostly FYI, plus a suggestion to perhaps use Github Actions to run tests on main branch?

If you want, this works really well for my other rust project:

```yaml
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --locked

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check
      - run: cargo clippy -- -Dwarnings
```
